---
title: "C2_W2_assignment"
author: "Thi NGUYEN"
date: "4/11/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("specdata_function/pollutantmean.R")
source("specdata_function/corr.R")
source("specdata_function/complete.R")

getwd()
setwd("/Users/nguyenthienthi/Documents/01_Personal/03_learning/2021_Data_Science_Coursera/datasciencecoursera/c2_w2")
```



### Question 1:
```{r}
pollutantmean("specdata", "nitrate", 70:72)
```

### Question 2:

```{r}
pollutantmean("specdata", "sulfate", 34)
```

### Question 3: 

```{r}
pollutantmean("specdata", "nitrate")
```


### Question 4:
```{r}
cc <- complete("specdata", c(6, 10, 20, 34, 100, 200, 310))
print(cc$nobs)
```

### Question 5:

```{r}
cc <- complete("specdata", 54)
print(cc$nobs)
```

### Question 6:
```{r}
RNGversion("3.5.1")  
set.seed(42)
cc <- complete("specdata", 332:1)
use <- sample(332, 10)
print(cc[use, "nobs"])
```

### Question 7
```{r}
cr <- corr("specdata")                
cr <- sort(cr)   
RNGversion("3.5.1")
set.seed(868)                
out <- round(cr[sample(length(cr), 5)], 4)
print(out)
```


### Question 8:
```{r}
cr <- corr("specdata", 129)                
cr <- sort(cr)                
n <- length(cr)    
RNGversion("3.5.1")
set.seed(197)                
out <- c(n, round(cr[sample(n, 5)], 4))
print(out)
```

### Question 9:
```{r}
cr <- corr("specdata", 2000)                
n <- length(cr)                
cr <- corr("specdata", 1000)                
cr <- sort(cr)
print(c(n, round(cr, 4)))
```

